config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :games, only: [:new, :create, :index, :edit] do
    member do
      get  'edit' => :edit
      post 'edit' => :handle_edit_post
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  GuessedCharacter = '*'.freeze

  def initialize
    super #QUESTION Rails models seem to need to call initialize on the base because of some sort of magic reason
    character_set = ['a','a','a','a','b','b','b','b','c','c','c','c','d','d','d','d','e','e','e','e']
    self.letters = '' #NOTE self. as letters is a member of the class. Just 'letters' will be treated as a local variable to the initialize method. letters comes from the schema via rails magic.
    random = Random.new(Time.now.to_i)
    while character_set.length > 0 do
      index = random.rand(0..character_set.length-1)
      self.letters << character_set[index]
      character_set.delete_at(index)
    end
  end

  def guess(index, other_index)
    #TODO guard clauses - out of range checks etc

    index -= 1 #TODO assuming input is in 1-based on 0-based
    other_index -= 1

    letter_array = self.letters.split('')
    if letter_array[index] == letter_array[other_index]
      letter_array[index] = Game::GuessedCharacter
      letter_array[other_index] = Game::GuessedCharacter
      self.letters = letter_array.join('')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new

  end

  def create
      game = Game.new
      game.save
  end

  def index
    @games = Game.all
  end

  def edit
    #TODO can't-find-it case
    id = params[:id] #QUESTION is just 'knowing' that there will be an Id parameter in the collection okay?
    @game = Game.find(id)
  end

  def handle_edit_post
    id = params[:id]
    @game = Game.find(id)

    index = params[:index].to_i
    other_index = params[:other_index].to_i

    #Do things to the game state
    if index != nil && other_index != nil # user has taken a guess (rather than navigated to the page via index or )
      @game.guess(index,other_index)
      @game.save
    end

    #TODO user feedback

    redirect_to url_for(:controller => :games, :action => :edit)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @date = Date.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper

  def get_clue(game_state_string)
    clue = ''
    letter_array = game_state_string.split('')
    letter_array.each do |letter|
      clue << (letter == Game::GuessedCharacter ? Game::GuessedCharacter : '?')
    end
    clue
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/edit.erb
<%= form_tag({:controller=>"games", :action=>"edit"}, method: :post) do %>
  <%= get_clue(@game.letters) %>
  <%= number_field_tag :index %>
  <%= number_field_tag :other_index %>
  <%= submit_tag 'Guess', name: nil %>
<% end %>



TODO let user guess letters

app/views/games/index.erb
<% @games.each do |game|%>
  <%= link_to "Game #{game.id}", [:edit, game] %>
<% end %>

app/views/games/new.erb
<%= button_to "Create Game", action: "create" %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Home page", home_index_url %>
<%= link_to "New game", new_game_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMemory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>